apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api/products  # Percorso per le chiamate al servizio backend
        pathType: Prefix
        backend:
          service:
            name: product-backend-service  # Nome del tuo servizio backend
            port:
              number: 8080  # Porta su cui il tuo servizio backend è esposto
