# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: product-backend-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: product-backend
#   template:
#     metadata:
#       labels:
#         app: product-backend
#     spec:
#       containers:
#         - name: product-backend
#           image: giovannimbesi/product-backend:latest
#           imagePullPolicy: Always
#           ports:
#             - name: http
#               containerPort: 8080 
#           env:
#             - name: SPRING_DATASOURCE_URL
#               value: "jdbc:mysql://productdb.cncw2muw0bl9.us-east-1.rds.amazonaws.com:3307/productDB"
#               #value: "jdbc:mysql://mysql-service:3306/springBoot"

#             - name: SPRING_DATASOURCE_USERNAME
#               value: "root"
#             - name: SPRING_DATASOURCE_PASSWORD
#               value: "giovanni"

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: product-backend-service
# spec:
#   selector:
#     app: product-backend
#   ports:
#     - protocol: "TCP"
#       port: 8080 
#       targetPort: 8080 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-backend
  template:
    metadata:
      labels:
        app: product-backend
    spec:
      containers:
        - name: product-backend
          image: giovannimbesi/product-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://productdb.cncw2muw0bl9.us-east-1.rds.amazonaws.com:3307/productDB"
              # value: "jdbc:mysql://mysql-service:3306/springBoot"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "giovanni"

---

apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
spec:
  selector:
    app: product-backend
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort




