version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: giovanni
      MYSQL_DATABASE: springBoot


  productBackend:
      build:
        context: ./productBackend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springBoot
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: giovanni
        SPRING_DATASOURCE_TEST-ON-BORROW: "true"
        SPRING_DATASOURCE_VALIDATION-QUERY: "SELECT 1"


  productFrontend:
      build:
        context: ./productFrontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api