---
- hosts: productEC2

  tasks:
    - name: Stop Minikube
      shell: "minikube stop"
      become: no

    - name: Delete Minikube
      shell: "minikube delete"
      become: no
    - name: Run minikube
      shell: "minikube start --driver=docker"
      become: no

    - name: Run bash script to deploy k8s cluster
      shell: "kubectl apply -f deployments"
      become: no

    - name: Wait for pods
      shell: "kubectl wait --for=condition=Ready pod --all --timeout=300s"
      become: no

    - name: Publish Services
      shell: "nohup kubectl port-forward svc/product-backend-service 8080:8080 --address 0.0.0.0 > /dev/null 2>&1 &
              nohup kubectl port-forward svc/product-frontend-service 3000:80 --address 0.0.0.0 > /dev/null 2>&1 &"
      become: no