
---

- hosts: productEC2
  become: true  
  tasks:
    - name: Run bash script to deploy k8s cluster
      shell: "sudo kubectl apply -f deployments"

    - name: Start port forwarding for backend service
      shell: "nohup kubectl port-forward service/product-backend-service 8080:8080 &"
      async: 0
      poll: 0

    - name: Start port forwarding for frontend service
      shell: "nohup kubectl port-forward service/product-frontend-service 3000:80 &"
      async: 0
      poll: 0


