---
- name: Run minikube script
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure minikube.sh has execute permission
      ansible.builtin.file:
        path: /home/ubuntu/minikube.sh
        mode: '0755'

    - name: Run minikube script
      ansible.builtin.command:
        cmd: ./minikube.sh
        chdir: /home/ubuntu
      become: true
