---

- hosts: productEC2
  become: true  

  tasks:

    - name: Esegui comando ls sulla macchina remota
      shell: ls
      register: result_ls
      become: true
      
    - name: Run bash script to deploy k8s cluster
      shell: "kubectl apply -f deployments/"

    - name: Start port forwarding for backend service
      shell: "nohup kubectl port-forward svc/product-backend-service 8080:8080 --address 0.0.0.0 &"
      async: 0
      poll: 0

    - name: Start port forwarding for frontend service
      shell: "nohup kubectl port-forward svc/product-frontend-service 3000:80 --address 0.0.0.0 &"
      async: 0
      poll: 0
