---
- hosts: productEC2

  tasks:
    - name: Stop Minikube
      shell: "minikube stop"
      become: no

    - name: Delete Minikube
      shell: "minikube delete"
      become: no
    - name: Run minikube
      shell: "minikube start --driver=docker"
      become: no

    - name: Run bash script to deploy k8s cluster
      shell: "kubectl apply -f deployments"
      become: no