
---
- hosts: productEC2
  become: true  

  tasks:
    - name: Stop Minikube
      shell: "minikube stop"
      become: no

    - name: Delete Minikube
      shell: "minikube delete"
      become: no

    - name: Run minikube
      shell: "minikube start --driver=docker"
      become: no

    - name: Run bash script to deploy k8s cluster
      shell: "./ansible/ansible_deploy_k8s/minikube.sh"
      become: no
    

#ansible-playbook -i inventory/inventory.ini playbook.yml
