name: ci-backend
run-name: 'Build product-backend (build version: ${{github.run_number}})'

on:
  push:
    branches:
      - "main"

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./productBackend//Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-backend:latest







