name: ci-backend
run-name: 'Build product-backend (build version: ${{github.run_number}})'

on:
  push:
    branches:
      - "main"

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Image 
        run: docker build -t product-backend ./productBackend/
      - name: Tag Docker Image
        run: docker tag product-backend giovannimbesi/product-backend:latest
      - name: Push Docker Image 
        run: docker push giovannimbesi/product-backend:latest






